# Base configs
baseurl: "http://www.wgilpin.com/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-52823035-5"

# UI configs
title: "Photography by William Gilpin"
subtitle: "WG"
author: "William Gilpin"
header:
 title: "Photography"
 subtitle: "by William Gilpin"
footer:
 name: "WG"
 bio: "xx."
 github: "https://www.github.com/williamgilpin"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/wgilpin0"
  github: "https://www.github.com/williamgilpin"
